"""
Security Remediation Agent
Analiza vulnerabilidades detectadas por Trivy/Checkov
y genera fixes automáticos via Pull Request
"""

import json
import os
import re
import base64
import requests


def call_groq(prompt: str, system: str) -> str:
    """Llama a la API de Groq con Llama 3.3 70B."""
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        raise ValueError("GROQ_API_KEY no está configurada")

    response = requests.post(
        "https://api.groq.com/openai/v1/chat/completions",
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json"
        },
        json={
            "model": "llama-3.3-70b-versatile",
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": prompt}
            ],
            "max_tokens": 1000,
            "temperature": 0.1
        },
        timeout=30
    )

    response.raise_for_status()
    return response.json()["choices"][0]["message"]["content"]


def analyze_vulnerability(vuln: dict) -> dict:
    """Analiza una vulnerabilidad y genera un fix recomendado."""
    system = """Eres un experto en seguridad DevSecOps.
    Analizas vulnerabilidades en contenedores Docker y generas fixes concisos.
    Responde SIEMPRE en este formato JSON exacto, sin texto adicional:
    {
        "risk_summary": "descripción del riesgo en 1-2 frases",
        "fix_type": "base_image_update|package_update|config_change",
        "fix_description": "qué cambiar exactamente",
        "urgency": "critical|high|medium|low",
        "pr_title": "título del PR en inglés, máximo 72 caracteres"
    }"""

    prompt = f"""Vulnerabilidad encontrada:
- CVE: {vuln.get('cve_id', 'N/A')}
- Paquete: {vuln.get('package', 'N/A')}
- Versión actual: {vuln.get('version', 'N/A')}
- Versión con fix: {vuln.get('fixed_version', 'N/A')}
- Severidad: {vuln.get('severity', 'N/A')}
- Imagen: {vuln.get('image', 'N/A')}

Analiza y genera el fix recomendado."""

    response = call_groq(prompt, system)

    json_match = re.search(r'\{.*\}', response, re.DOTALL)
    if json_match:
        return json.loads(json_match.group())

    return {
        "risk_summary": response[:200],
        "fix_type": "unknown",
        "fix_description": "Manual review required",
        "urgency": vuln.get('severity', 'medium').lower(),
        "pr_title": f"fix: address {vuln.get('cve_id', 'vulnerability')} in {vuln.get('package', 'package')}"
    }


def pr_already_exists(cve_id: str, repo: str, headers: dict) -> bool:
    """Verifica si ya existe un PR abierto para este CVE."""
    r = requests.get(
        f"https://api.github.com/repos/{repo}/pulls",
        headers=headers,
        params={"state": "open", "per_page": 100}
    )
    if r.status_code != 200:
        return False

    for pr in r.json():
        if cve_id.lower() in pr.get("title", "").lower():
            print(f"PR already exists for {cve_id}: {pr['html_url']}")
            return True
    return False


def ensure_labels_exist(repo: str, headers: dict):
    """Crea los labels si no existen."""
    labels = [
        {"name": "security", "color": "d73a4a", "description": "Security vulnerability fix"},
        {"name": "automated", "color": "0075ca", "description": "Automatically generated by AI agent"},
        {"name": "ai-generated", "color": "7057ff", "description": "Generated by Groq AI agent"}
    ]
    for label in labels:
        r = requests.post(
            f"https://api.github.com/repos/{repo}/labels",
            headers=headers,
            json=label
        )
        if r.status_code == 201:
            print(f"Label created: {label['name']}")
        elif r.status_code == 422:
            print(f"Label already exists: {label['name']}")
        else:
            print(f"Label error {r.status_code}: {label['name']}")


def create_github_pr(analysis: dict, vuln: dict, repo: str, token: str) -> str:
    """Crea un PR en GitHub con el fix recomendado."""

    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28"
    }

    # Verificar si ya existe un PR para este CVE
    if pr_already_exists(vuln.get('cve_id', ''), repo, headers):
        return f"SKIPPED: PR already exists for {vuln.get('cve_id')}"

    # Asegurar que los labels existen
    ensure_labels_exist(repo, headers)

    # Obtener SHA de main
    r = requests.get(
        f"https://api.github.com/repos/{repo}/git/refs/heads/main",
        headers=headers
    )
    r.raise_for_status()
    main_sha = r.json()["object"]["sha"]

    # Nombre de la rama
    cve_safe = vuln.get('cve_id', 'vuln').lower().replace('/', '-')
    branch_name = f"fix/security-{cve_safe}-{main_sha[:7]}"

    # Crear rama
    r = requests.post(
        f"https://api.github.com/repos/{repo}/git/refs",
        headers=headers,
        json={"ref": f"refs/heads/{branch_name}", "sha": main_sha}
    )
    if r.status_code not in [201, 422]:
        r.raise_for_status()
    print(f"Branch: {branch_name}")

    # Crear fichero de evidencia en la rama
    report_content = json.dumps({
        "cve_id": vuln.get("cve_id"),
        "package": vuln.get("package"),
        "current_version": vuln.get("version"),
        "fixed_version": vuln.get("fixed_version"),
        "severity": vuln.get("severity"),
        "analysis": analysis,
        "status": "pending_fix"
    }, indent=2)

    file_path = f"security-reports/{vuln.get('cve_id', 'vuln').replace('/', '-')}.json"

    r = requests.get(
        f"https://api.github.com/repos/{repo}/contents/{file_path}",
        headers=headers,
        params={"ref": branch_name}
    )
    existing_sha = r.json().get("sha") if r.status_code == 200 else None

    payload = {
        "message": f"security: add vulnerability report for {vuln.get('cve_id')}",
        "content": base64.b64encode(report_content.encode()).decode(),
        "branch": branch_name
    }
    if existing_sha:
        payload["sha"] = existing_sha

    r = requests.put(
        f"https://api.github.com/repos/{repo}/contents/{file_path}",
        headers=headers,
        json=payload
    )
    r.raise_for_status()
    print(f"File created: {file_path}")

    # Cuerpo del PR
    pr_body = f"""## 🔒 Security Vulnerability Fix

**Automated PR generated by AI Security Agent**

### Vulnerability Details
| Field | Value |
|-------|-------|
| CVE | `{vuln.get('cve_id', 'N/A')}` |
| Package | `{vuln.get('package', 'N/A')}` |
| Current Version | `{vuln.get('version', 'N/A')}` |
| Fixed Version | `{vuln.get('fixed_version', 'N/A')}` |
| Severity | `{vuln.get('severity', 'N/A')}` |

### AI Risk Analysis
{analysis.get('risk_summary', 'N/A')}

### Recommended Fix
**Type:** {analysis.get('fix_type', 'N/A')}

{analysis.get('fix_description', 'N/A')}

### Urgency
**{analysis.get('urgency', 'medium').upper()}**

---
*This PR was automatically generated by the Security Remediation Agent*
*Powered by Groq (Llama 3.3 70B) · {vuln.get('image', 'N/A')}*"""

    # Crear PR con labels
    r = requests.post(
        f"https://api.github.com/repos/{repo}/pulls",
        headers=headers,
        json={
            "title": analysis.get('pr_title', f"fix: address {vuln.get('cve_id')}"),
            "body": pr_body,
            "head": branch_name,
            "base": "main",
            "labels": ["security", "automated", "ai-generated"]
        }
    )
    r.raise_for_status()

    pr_url = r.json()["html_url"]

    # Añadir labels al PR
    pr_number = r.json()["number"]
    requests.post(
        f"https://api.github.com/repos/{repo}/issues/{pr_number}/labels",
        headers=headers,
        json={"labels": ["security", "automated", "ai-generated"]}
    )

    return pr_url


def handler(event, context):
    """Lambda handler principal."""
    print(f"Event received: {json.dumps(event)}")

    vulnerabilities = event.get("vulnerabilities", [])
    repo = event.get("repo", "")
    github_token = event.get("github_token", "")

    if not vulnerabilities:
        return {
            "statusCode": 200,
            "body": json.dumps({"message": "No vulnerabilities to process"})
        }

    results = []

    for vuln in vulnerabilities[:3]:
        try:
            print(f"Analyzing: {vuln.get('cve_id')} in {vuln.get('package')}")
            analysis = analyze_vulnerability(vuln)
            print(f"Analysis: {json.dumps(analysis)}")

            pr_url = None
            if github_token and repo:
                pr_url = create_github_pr(analysis, vuln, repo, github_token)
                print(f"PR result: {pr_url}")

            results.append({
                "cve_id": vuln.get("cve_id"),
                "analysis": analysis,
                "pr_url": pr_url,
                "status": "success"
            })

        except Exception as e:
            print(f"Error processing {vuln.get('cve_id')}: {str(e)}")
            results.append({
                "cve_id": vuln.get("cve_id"),
                "error": str(e),
                "status": "error"
            })

    return {
        "statusCode": 200,
        "body": json.dumps({
            "processed": len(results),
            "results": results
        })
    }
