"""
Security Remediation Agent
Analiza vulnerabilidades detectadas por Trivy/Checkov
y genera fixes automáticos via Pull Request
"""

import json
import os
import re
import requests


def call_groq(prompt: str, system: str) -> str:
    """Llama a la API de Groq con Llama 3.3 70B."""
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        raise ValueError("GROQ_API_KEY no está configurada")

    response = requests.post(
        "https://api.groq.com/openai/v1/chat/completions",
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json"
        },
        json={
            "model": "llama-3.3-70b-versatile",
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": prompt}
            ],
            "max_tokens": 1000,
            "temperature": 0.1
        },
        timeout=30
    )

    response.raise_for_status()
    return response.json()["choices"][0]["message"]["content"]


def analyze_vulnerability(vuln: dict) -> dict:
    """
    Analiza una vulnerabilidad y genera un fix recomendado.
    """
    system = """Eres un experto en seguridad DevSecOps.
    Analizas vulnerabilidades en contenedores Docker y generas fixes concisos.
    Responde SIEMPRE en este formato JSON exacto, sin texto adicional:
    {
        "risk_summary": "descripción del riesgo en 1-2 frases",
        "fix_type": "base_image_update|package_update|config_change",
        "fix_description": "qué cambiar exactamente",
        "urgency": "critical|high|medium|low",
        "pr_title": "título del PR en inglés, máximo 72 caracteres"
    }"""

    prompt = f"""Vulnerabilidad encontrada:
- CVE: {vuln.get('cve_id', 'N/A')}
- Paquete: {vuln.get('package', 'N/A')}
- Versión actual: {vuln.get('version', 'N/A')}
- Versión con fix: {vuln.get('fixed_version', 'N/A')}
- Severidad: {vuln.get('severity', 'N/A')}
- Imagen: {vuln.get('image', 'N/A')}

Analiza y genera el fix recomendado."""

    response = call_groq(prompt, system)

    json_match = re.search(r'\{.*\}', response, re.DOTALL)
    if json_match:
        return json.loads(json_match.group())

    return {
        "risk_summary": response[:200],
        "fix_type": "unknown",
        "fix_description": "Manual review required",
        "urgency": vuln.get('severity', 'medium').lower(),
        "pr_title": f"fix: address {vuln.get('cve_id', 'vulnerability')} in {vuln.get('package', 'package')}"
    }


def create_github_pr(analysis: dict, vuln: dict, repo: str, token: str) -> str:
    """Crea un PR en GitHub con el fix recomendado."""

    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28"
    }

    # Obtener SHA de main
    r = requests.get(
        f"https://api.github.com/repos/{repo}/git/refs/heads/main",
        headers=headers
    )
    r.raise_for_status()
    main_sha = r.json()["object"]["sha"]

    # Crear branch
    branch_name = f"fix/security-{vuln.get('cve_id', 'vuln').lower().replace('/', '-')}-{main_sha[:7]}"

    requests.post(
        f"https://api.github.com/repos/{repo}/git/refs",
        headers=headers,
        json={"ref": f"refs/heads/{branch_name}", "sha": main_sha}
    )

    print(f"Branch creado: {branch_name}")

    # Cuerpo del PR
    pr_body = f"""## 🔒 Security Vulnerability Fix

**Automated PR generated by AI Security Agent**

### Vulnerability Details
| Field | Value |
|-------|-------|
| CVE | `{vuln.get('cve_id', 'N/A')}` |
| Package | `{vuln.get('package', 'N/A')}` |
| Current Version | `{vuln.get('version', 'N/A')}` |
| Fixed Version | `{vuln.get('fixed_version', 'N/A')}` |
| Severity | `{vuln.get('severity', 'N/A')}` |

### AI Risk Analysis
{analysis.get('risk_summary', 'N/A')}

### Recommended Fix
**Type:** {analysis.get('fix_type', 'N/A')}

{analysis.get('fix_description', 'N/A')}

### Urgency
**{analysis.get('urgency', 'medium').upper()}**

---
*This PR was automatically generated by the Security Remediation Agent*
*Powered by Groq (Llama 3.3 70B) · {vuln.get('image', 'N/A')}*"""

    # Crear PR
    r = requests.post(
        f"https://api.github.com/repos/{repo}/pulls",
        headers=headers,
        json={
            "title": analysis.get('pr_title', f"fix: address {vuln.get('cve_id', 'vulnerability')}"),
            "body": pr_body,
            "head": branch_name,
            "base": "main"
        }
    )
    r.raise_for_status()
    return r.json()["html_url"]


def handler(event, context):
    """
    Lambda handler principal.

    Evento esperado:
    {
        "vulnerabilities": [...],
        "repo": "usuario/repo",
        "github_token": "ghp_..."
    }
    """
    print(f"Event received: {json.dumps(event)}")

    vulnerabilities = event.get("vulnerabilities", [])
    repo = event.get("repo", "")
    github_token = event.get("github_token", "")

    if not vulnerabilities:
        return {
            "statusCode": 200,
            "body": json.dumps({"message": "No vulnerabilities to process"})
        }

    results = []

    for vuln in vulnerabilities[:3]:
        try:
            print(f"Analyzing: {vuln.get('cve_id')} in {vuln.get('package')}")
            analysis = analyze_vulnerability(vuln)
            print(f"Analysis: {json.dumps(analysis)}")

            pr_url = None
            if github_token and repo:
                pr_url = create_github_pr(analysis, vuln, repo, github_token)
                print(f"PR created: {pr_url}")

            results.append({
                "cve_id": vuln.get("cve_id"),
                "analysis": analysis,
                "pr_url": pr_url,
                "status": "success"
            })

        except Exception as e:
            print(f"Error processing {vuln.get('cve_id')}: {str(e)}")
            results.append({
                "cve_id": vuln.get("cve_id"),
                "error": str(e),
                "status": "error"
            })

    return {
        "statusCode": 200,
        "body": json.dumps({
            "processed": len(results),
            "results": results
        })
    }
